apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: tassedocr.azurecr.io/app1:latest
        ports:
        - containerPort: 8080
        env:
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: app1-secrets
                key: SESSION_SECRET
          - name: TENANT_ID
            valueFrom:
              secretKeyRef:
                name: app1-secrets
                key: TENANT_ID
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: app1-secrets
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: app1-secrets
                key: CLIENT_SECRET
          - name: REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: app1-secrets
                key: REDIRECT_URI
